file_format: "1"
id: pulso
name: PULSO
type: shield
url: https://github.com/GEIGEIGEIST/TOTEM
requires: 
  - seeeduino_xiao_ble
  - pro_micro
exposes:
  - i2c_oled
features:
  - keys
siblings:
  - pulso_dongle
  - pulso_left
# - pulso_left_peripheral
  - pulso_right