include:
  - board: seeeduino_xiao_ble
    shield: pulso_left
  - board: seeeduino_xiao_ble
    shield: pulso_right
  - board: nice_nano
    shield: pulso_dongle
# there is no settingsreset (needed) for the XIAO
